function Hd = untitled0
%UNTITLED0 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.2 and the DSP System Toolbox 8.5.
% Generated on: 24-Nov-2014 19:52:17

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 5000;  % Sampling Frequency

N    = 173;      % Order
Fc   = 500;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
